### ISSUE TITLE
Error: Use of uninitialized value...

### ISSUE THREAD

**Issue by pneumowidow** [egonozer/in_silico_pcr#3]
Hi, 

I've been trying to use your script to extract sequences but I keep getting the following errors:

```
Use of uninitialized value in substr at in_silico_PCR.pl line 357.
Use of uninitialized value in addition (+) at in_silico_PCR.pl line 377.

```
I thought it had something to do with the multiple scaffolds in the fasta files, so I used artemis to extract the exact amplicon with both primers at the start and the end of the sequence and tries again, but I still got no output and the same errors above. I've looked online to try to figure out what the problem is, but can't seem to find a solution. I am not a perl user, so I'm completely out of my element here. Can you please help me out?

Thank you

**Comment by egonozer** [comment]
I did some testing and found that you'll get that error if the forward primer sequence is found at the very end of the input sequence. This error doesn't pop up if you use the -c option, but it still shouldn't be there. I dropped a quick fix as version 0.5.1.

**Comment by pneumowidow** [comment]
It works now with the -c option. Thank you very much. I didn't see that earlier

**Comment by hkaspersen** [comment]
Hello @egonozer !
I am currently using version 0.6, I am getting a similar error in the `2> *fasta` output with my data as well, even though I am running with the `-c` parameter:

```
Use of uninitialized value $rev in substitution (s///) at /cluster/projects/nn9305k/src/in_silico_pcr/in_silico_PCR.pl line 184, <$pin> line 1.
Use of uninitialized value $rev in substitution (s///) at /cluster/projects/nn9305k/src/in_silico_pcr/in_silico_PCR.pl line 184, <$pin> line 2.
Use of uninitialized value $rev in substitution (s///) at /cluster/projects/nn9305k/src/in_silico_pcr/in_silico_PCR.pl line 184, <$pin> line 3.
Use of uninitialized value $primer2 in uc at /cluster/projects/nn9305k/src/in_silico_pcr/in_silico_PCR.pl line 209.
Use of uninitialized value $primer2 in uc at /cluster/projects/nn9305k/src/in_silico_pcr/in_silico_PCR.pl line 209.
```

Command used:
`perl /cluster/projects/nn9305k/src/in_silico_pcr/in_silico_PCR.pl -s $inputfile -p $primers -c > ${output}/${outfile}_insilicopcr_controls.tsv 2> ${output}/${outfile}_amplicons_controls.fasta`

When I do run it with the `-c` parameter, it always gets an OOM kill, even with over 150Gb of memory (These are small bacterial genomes of around 2Mbp, with only 2 primer sets), so something is definately not working. 
Without the `-c` I still get the same messages, but I also get a result of "No amplification", even though I have positive controls that should have these targets.

Any idea what may be wrong here?
